spring:
  application:
    name: "gatewayserver"
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true

logging:
  level:
    com:
      kduytran:
        gatewayserver: DEBUG

info:
  app:
    name: "gatewayserver"
    description: "Bank Gateway Server Application"
    version: "1.0.0"

server:
  port: 8072

olp:
  front-end-urls: "http://localhost:5173"

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: "http://localhost:8070/eureka/"
