spring:
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: "category-consumers"
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
    producer:
      bootstrap-servers: localhost:29092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
            add:
              type:
                headers: false
  application:
    name: "category"
  datasource:
    url: jdbc:postgresql://localhost:5434/category_db
    driver-class-name: org.postgresql.Driver
    username: user
    password: password
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      schema-locations: classpath:/schema.sql
      mode: always
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    bus:
      enabled: true
    stream:
      kafka:
        binder:
          brokers: localhost:29092

server:
  port: 8100

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

info:
  app:
    name: "category"
    description: "Category Service"
    version: "1.0.0"

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: "http://localhost:8070/eureka/"


logging:
  level:
    com.kduytran.categoryservice: debug
