services:
  postgres_user_db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_db
    volumes:
      - pg_user_data:/var/lib/postgresql/data
    networks:
      - "db_test"
    ports:
      - "5433:5432"
  postgres_category_db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: category_db
    volumes:
      - pg_category_data:/var/lib/postgresql/data
    networks:
      - "db_test"
    ports:
      - "5434:5432"
  postgres_class_db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: class_db
    volumes:
      - pg_class_data:/var/lib/postgresql/data
    networks:
      - "db_test"
    ports:
      - "5435:5432"
  postgres_class_query_db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: class_query_db
    volumes:
      - pg_class_query_data:/var/lib/postgresql/data
    networks:
      - "db_test"
    ports:
      - "5436:5432"
  postgres_class_resource_db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: class_resource_db
    volumes:
      - pg_class_resource_data:/var/lib/postgresql/data
    networks:
      - "db_test"
    ports:
      - "5437:5432"
  postgres_order_db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: order_db
    volumes:
      - pg_order_data:/var/lib/postgresql/data
    networks:
      - "db_test"
    ports:
      - "5438:5432"
  postgres_payment_db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: payment_db
    volumes:
      - pg_payment_data:/var/lib/postgresql/data
    networks:
      - "db_test"
    ports:
      - "5439:5432"
  postgres_member_db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: member_db
    volumes:
      - pg_member_data:/var/lib/postgresql/data
    networks:
      - "db_test"
    ports:
      - "5440:5432"
  postgres_request_db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: request_db
    volumes:
      - pg_request_data:/var/lib/postgresql/data
    networks:
      - "db_test"
    ports:
      - "5441:5432"
  postgres_pricing_db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pricing_db
    volumes:
      - pg_pricing_data:/var/lib/postgresql/data
    networks:
      - "db_test"
    ports:
      - "5442:5432"

networks:
  db_test:
    driver: "bridge"

volumes:
  pg_user_data:
    name: pg_user_data
  pg_category_data:
    name: pg_category_data
  pg_class_data:
    name: pg_class_data
  pg_class_query_data:
    name: pg_class_query_data
  pg_class_resource_data:
    name: pg_class_resource_data
  pg_order_data:
    name: pg_order_data
  pg_payment_data:
    name: pg_payment_data
  pg_member_data:
    name: pg_member_data
  pg_request_data:
    name: pg_request_data
  pg_pricing_data:
    name: pg_pricing_data
  pg_keycloak_data:
    name: pg_keycloak_data
