spring:
  application:
    name: 'auth-management-service'
  config:
    import: "optional:configserver:http://localhost:8071/"

server:
  port: 8160

management:
  info:
    env:
      enabled: true
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
    shutdown:
      enabled: true

info:
  app:
    name: "auth-management-service"
    description: "Auth Management Service"
    version: "1.0.0"

logging:
  level:
    com.kduytran.authmanagementservice: debug

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: "http://localhost:8070/eureka/"
