spring:
  application:
    name: 'auth-management-service'
  config:
    import: "optional:configserver:http://localhost:8071/"

server:
  port: 8160

management:
  info:
    env:
      enabled: true
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
    shutdown:
      enabled: true

info:
  app:
    name: "auth-management-service"
    description: "Auth Management Service"
    version: "1.0.0"

logging:
  level:
    com.kduytran.authmanagementservice: debug

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: "http://localhost:8070/eureka/"

keycloak:
  auth-server-url: http://localhost:8180
  realm: online-learning-platform
  resource: olp-client # Client ID
  ssl-required: none
  use-resource-role-mappings: true
  bearer-only: true
  cors: true
  principal-attribute: preferred_username

keycloak-config:
  client-secret: 68xszkoyUm0aFgT0PWeAxy5WC4hTQM6P # TODO: Need to hide or encrypt it
