spring:
  application:
    name: "class-query"
  config:
    import: "optional:configserver:http://localhost:8071/"
  kafka:
    bootstrap-servers: localhost:29092
    streams:
      application-id: class-query-service-app
      bootstrap-servers: localhost:29092
      default:
        key-serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        value-serde: com.kduytran.classqueryservice.event.JsonSerde
      auto-startup: true
      properties:
        processing.guarantee: exactly_once
        max.block.ms: 50000
    consumer:
      group-id: "class-query-consumers"
      auto-offset-reset: earliest
      properties:
        "spring.json.trusted.packages": "*"
  datasource:
    url: jdbc:postgresql://localhost:5436/class_query_db
    driver-class-name: org.postgresql.Driver
    username: user
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    bus:
      enabled: true
    stream:
      kafka:
        binder:
          brokers: localhost:29092

server:
  port: 8130

management:
  info:
    env:
      enabled: true
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
    shutdown:
      enabled: true

info:
  app:
    name: "class-query"
    description: "Class query service"
    version: "1.0.0"

logging:
  level:
    com.kduytran.classqueryservice: debug

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: "http://localhost:8070/eureka/"