services:
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    environment:
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://:29092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_NUM_PARTITIONS=1
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=false
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LOG_DIRS=/bitnami/kafka/data
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
    ports:
      - "9092:9092"
      - "29092:29092"
    volumes:
      - ./volume/kafka:/bitnami/kafka
    networks:
      - test-env
  olp_test_db:
    image: bitnami/postgresql:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: "olp_test_db"
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_INITDB_ARGS: --auth-host=scram-sha-256
    volumes:
      - olp_test_db:/bitnami/postgresql
    networks:
      - "test-env"
    ports:
      - "5436:5432"
  redis:
    container_name: redis
    image: redis:7.4.1-alpine
    restart: always
    ports:
      - '6379:6379'
    volumes: 
      - ./volume/redis:/data
    networks:
      - "test-env"
  zipkin:
    image: ghcr.io/openzipkin/zipkin-slim:${TAG:-latest}
    restart: always
    container_name: zipkin
    # Environment settings are defined here https://github.com/openzipkin/zipkin/blob/master/zipkin-server/README.md#environment-variables
    environment:
      - STORAGE_TYPE=mem
      # Uncomment to enable self-tracing
      # - SELF_TRACING_ENABLED=true
      # Uncomment to increase heap size
      # - JAVA_OPTS=-Xms128m -Xmx128m -XX:+ExitOnOutOfMemoryError
    ports:
      # Port used for the Zipkin UI and HTTP Api
      - "9411:9411"
  prometheus:
    image: prom/prometheus
    restart: always
    container_name: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  otel-collector:
    image: otel/opentelemetry-collector-contrib
    restart: always
    command:
      - --config=/etc/otelcol-contrib/config.yml
    volumes:
      - ./otel-collector.yaml:/etc/otelcol-contrib/config.yml
    ports:
      - "1888:1888" # pprof extension
      - "8888:8888" # Prometheus metrics exposed by the Collector
      - "8889:8889" # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP http receiver
      - "55679:55679" # zpages extension
    depends_on:
      - prometheus
      - zipkin
      - jaeger
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14250"
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./volume/grafana/entrypoint.sh:/app/entrypoint.sh
      - ./volume/grafana/config/dashboards:/var/lib/grafana/dashboards
      - ./volume/grafana/config/datasources:/etc/grafana/datasources
      - ./volume/grafana/config/plugins:/var/lib/grafana/plugins
      - ./volume/grafana/grafana_data:/var/lib/grafana

networks:
  test-env:
    driver: bridge

volumes:
  olp_test_db:
